name: Build and deploy app to dev
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pia
          tag: latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy:
    strategy:
      matrix:
        cluster: [dev, prod]
    name: Deploy to ${{ matrix.cluster }}-gcp
    permissions:
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy application to ${{ matrix.cluster }}-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: ${{ needs.build.outputs.image }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/nais.yaml

  trivy-scan:
    name: Scanner docker image med Trivy
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      contents: read # to write sarif
      security-events: write # push sarif to GitHub security
      id-token: write # for nais/login
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/pia-actions/trivy-scan@v1 # https://github.com/navikt/pia-actions/tree/main/trivy-scan
        with:
          image: ${{ needs.build.outputs.image }}
          team: pia
